#ifndef CONFIG_H
#define CONFIG_H

#define EMULATOR_WINDOW_TITLE "Chip8"
#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_PROGRAM_LOAD_ADDRESS 0x200
#define CHIP8_WIDTH 64
#define CHIP8_HEIGHT 32
#define EMULATOR_WINDOW_SCALER 10

#define CHIP8_NUMBER_OF_DATA_REGISTERS 16
#define CHIP8_STACK_SIZE 16

#define CHIP8_NUMBER_OF_KEYS 16

#define CHIP8_CHAR_SET_LOAD_ADDRESS 0x000
#define CHIP8_DEFAULT_SPRITE_HEIGHT 5
#endif